# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangologin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pwrd',
            new_name='pword',
        ),
    ]
